### PR TITLE
Spd tests

### LINKED ISSUE #31: Symmetric and positive definite linear systems
@abuttari

The small examples in the documentation are working : [Tutorials](https://juliasmoothoptimizers.github.io/qr_mumps.jl/dev/tutorials/#Symmetric-and-positive-definite-linear-systems).
However the tests for symmetric and positive definite linear systems don't passed : [Tests](https://github.com/JuliaSmoothOptimizers/qr_mumps.jl/blob/master/test/test_qrm.jl#L280-L420).

I suspect a bug in the C / Fortran code.

**Remark** : a `int  zqrm_square_solve_c(struct zqrm_spfct_type_c *qrm_spfct_c, const char transp, double _Complex *b, const int nrhs)` routine could be relevant for solving in-place triangular systems when we want to solve square (symmetric positive definite) linear systems.

### PR DESCRIPTION
**Pull request by abuttari**
This one should fix the testing of Hermitian positive definite problems which did not pass due to these three bugs:

- The generated matrices could possibly be undefinite
- input arguments where not protected by a copy() in calls to solve methods with !
- there was a bug in qr_mumps which is fixed in the 3.0.2beta bersion

fix #31

### CODE REVIEW

**Comment by amontoison** [comment]
Thanks @abuttari !
Do you want that I recompile `qr_mumps` with Yggdrasil to see if the tests passed now or we wait the official release 3.0.2 ?

**Comment by abuttari** [comment]
> Thanks @abuttari !
> Do you want that I recompile `qr_mumps` with Yggdrasil to see if the tests passed now or we wait the official release 3.0.2 ?

@amontoison I uploaded a new qr_mumps-3.0.2.tgz file and did

```
] update qr_mumps_jll
] test qr_mumps

```
and all the tests passed. Is this enough?

**Comment by amontoison** [comment]
No, this not enough because you provide `ENV["JULIA_QR_MUMPS_LIBRARY_PATH"]` and it's your local version of `qr_mumps` that is used for the tests.

**Comment by abuttari** [comment]
> No, this not enough because you provide `ENV["JULIA_QR_MUMPS_LIBRARY_PATH"]` and it's your local version of `qr_mumps` that is used for the tests.

I didn't use `ENV["JULIA_QR_MUMPS_LIBRARY_PATH"]`  but I might have updated the qr_mumps-3.0.2.tgz later than when the above check were run. Can you re-trigger them?

**Comment by amontoison** [comment]
To update `qr_mumps_jll` we must recompile it with Yggdrasil. I can do it now, it takes 2min. Can you just rebase your branch ?
```
git fetch upstream master
git rebase upstream/master
.... # remove conflicts
git add my_files_with_conflicts.jl
git rebase  --continue
git push -f
```

**Comment by amontoison** [comment]
Perfect Alfredo !
When https://github.com/JuliaPackaging/Yggdrasil/pull/2742 is merged, I will re-trigger the tests and the new `jll` with your fixes will be used by default.

**Comment by amontoison** [comment]
All tests passed :rocket:

**Pull request merged**
